default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main,ext-all]

  javascripts:    [ext-base,ext-all]

  has_layout:     true
  layout:         layout
