all:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css]

  javascripts:    [/djs/installer/main.js,/djs/installer/layout.js,/djs/installer/mainWindow.js,/djs/installer/firstTab.js, /djs/installer/secondTab.js, /djs/installer/installerSettingsTab.js, /djs/installer/startTab.js]

  has_layout:     true
  layout:         layout
