prod:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: mysql:host=mysqlprod.rotex.de;dbname=cuteflow_v3
      username: cuteflow_v3
      password: iusdamn31&&817!%


dev:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: mysql:host=localhost;dbname=cuteflow_v3
      username: root
      password: 
